#!/usr/bin/bash

declare -A SWITCHES
SWITCHES[MEDIA_KEYS]=["$(xmodmap -pke | grep XF86Audio)"]
SWITCHES[SLEEP_KEY]=["$(xmodmap -pke | grep XF86Sleep)"]
SWITCHES[BATTERY]=["$(ls /sys/class/power_supply | grep BAT)"]

declare -a PATS
ind=0
for switch in ${!SWITCHES[@]}; do
    if [ $switch ]; then
        PATS[$ind]="-e s/\[\[$switch:(.*)\?(.*)\]\]/\2/g"
    else
        PATS[$ind]="-e s/\[\[$switch:(.*)\?(.*)\]\]/\1/g"
    fi
    ind=$ind+1
done

# usage: bang <dir> <target>
bang() {
    mkdir -p $2
    for input in $(find $1 -mindepth 1 -maxdepth 1 -name '*.in' -type f); do
        out=${input%%.in}
        src=$input
        #echo "sed -r ${PATS[*]} <$src >$out"
        sed -r ${PATS[*]} <$src >$out
    done
    for link in $(find $1 -mindepth 1 -maxdepth 1 -name '*.ln' -type f); do
        target=$(basename $link .ln)
        echo "$link -> $2/$target"
        ln -fs $link $2/$target
    done
    for subdir in $(find $1 -mindepth 1 -maxdepth 1 ! -path '*.git*' -type d); do
        if [[ -e $subdir/.target ]]; then
            bang $subdir $2/$(cat $subdir/.target)
        else
            bang $subdir $2
        fi
    done
}

bang ${1:-$HOME/.dot} ${2:-$HOME}
