#!/usr/bin/bash
go=true
while getopts ":d" opt; do
    case "$opt" in
        d)
            go=false
            ;;
        \?)
            echo "usage: link [-d]"
            exit 1
            ;;
    esac
done
shift $((OPTIND-1))

link() {
    [[ -e $1/.target ]] && eval PVD=$(cat $1/.target)
    for link in $(find $1 -mindepth 1 -maxdepth 1 -name '*.ln' -type f); do
        name=$(basename $link .ln)
        lexpr=$(head -n 1 $link | sed -r 's/.*link:(.*)|.*/\1/g')
        if [[ "$lexpr" ]]; then
            case "$lexpr" in
                dot)
                    target=.$name
                    ;;
                no|none|skip)
                    continue
                    ;;
                *)
                    eval target="$lexpr"
                    ;;
            esac
        elif [[ -e ${link%%.ln}.target ]]; then
            eval target=$(cat ${link%%.ln}.target)
        else
            target=$name
        fi
        $verbose && echo "$link → $PVD/$target"
        $go && ln -fs $link $PVD/$target
    done
    for subdir in $(find $1 -mindepth 1 -maxdepth 1 ! -path '*.git*' -type d); do
        [[ -e $1/.target ]] && eval PVD=$(cat $1/.target)
        link $subdir
    done
}

ROOT=${1:-$HOME/.dot}
link $ROOT
