#!/bin/bash
source $HOME/.config/panel/config

# borders and gaps
bspc config border_width 2
bspc config window_gap 10
bspc config bottom_padding 0
bspc config top_padding $(($height+$y))

# le pretty colors
focused_color="#33b5e1" # base 0D
active_color="#667581" # base 03
normal_color="#667581" # base 00
presel_color="#d73c9a" # base 0F
urgent_color="#ef5253" # base 08

bspc config focused_border_color "$focused_color"
bspc config active_border_color "$active_color"
bspc config normal_border_color "$normal_color"
bspc config presel_feedback_color "$presel_color"

bspc config borderless_monocle false
bspc config gapless_monocle    false

# focus
bspc config focus_follows_pointer true
bspc config pointer_follows_monitor false

# setup monitors
bspc monitor -d I II III IV V VI VII VIII IX X

# rules
bspc rule -a dialog floating=on
bspc rule -a zathura tiled=on

# misc
bspc config ignore_ewmh_focus true
bspc config honor_size_hints false
